export const demoDashboardOverview = {
  period: {
    date_from: '2026-03-26T00:00:00Z',
    date_to: '2026-04-01T00:00:00Z',
  },
  equipment: {
    total_count: 48,
    buckets: {
      normal: 31,
      warning: 11,
      critical: 6,
    },
  },
  events: {
    total_count: 94,
    buckets: {
      warning: 41,
      critical: 18,
      recovery: 35,
    },
  },
  maintenance: {
    total_count: 27,
    buckets: {
      overdue: 4,
      due_today: 6,
      planned: 17,
    },
  },
  notifications: {
    total_count: 56,
    buckets: {
      unread: 12,
      internal: 35,
      email: 21,
    },
  },
}

export const demoEquipmentStatusAnalytics = {
  total_count: 48,
  by_status: {
    normal: 31,
    warning: 11,
    critical: 6,
  },
  by_type: [
    {
      equipment_type_id: 'demo-haul-truck',
      equipment_type_name: 'Самосвал',
      total_count: 18,
      by_status: {
        normal: 12,
        warning: 4,
        critical: 2,
      },
    },
    {
      equipment_type_id: 'demo-excavator',
      equipment_type_name: 'Экскаватор',
      total_count: 16,
      by_status: {
        normal: 10,
        warning: 4,
        critical: 2,
      },
    },
    {
      equipment_type_id: 'demo-drill',
      equipment_type_name: 'Буровая установка',
      total_count: 14,
      by_status: {
        normal: 9,
        warning: 3,
        critical: 2,
      },
    },
  ],
}

export const demoEventAnalytics = {
  period: {
    date_from: '2026-03-26T00:00:00Z',
    date_to: '2026-04-01T00:00:00Z',
  },
  total_count: 94,
  by_severity: {
    info: 19,
    warning: 57,
    critical: 18,
  },
  by_event_type: {
    parameter_warning: 36,
    parameter_critical: 18,
    equipment_warning: 13,
    equipment_critical: 8,
    equipment_recovered: 19,
  },
  timeline: [
    { date: '2026-03-26', count: 8 },
    { date: '2026-03-27', count: 12 },
    { date: '2026-03-28', count: 16 },
    { date: '2026-03-29', count: 14 },
    { date: '2026-03-30', count: 18 },
    { date: '2026-03-31', count: 11 },
    { date: '2026-04-01', count: 15 },
  ],
}

export const demoEquipmentList = [
  {
    id: 'demo-eq-1',
    name: 'Экскаватор EX-204',
    code: 'EX-204',
    serial_number: 'SN-EX-204',
    location: 'Северный карьер / Сектор A2',
    description: 'Основная экскаваторная единица для снятия вскрышных пород.',
    specifications: {
      engine_power_kw: 710,
      bucket_capacity_m3: 5.4,
      weight_tons: 92,
    },
    is_active: true,
    equipment_type: {
      id: 'demo-excavator',
      name: 'Экскаватор',
      code: 'EXC',
      description: 'Гусеничный гидравлический экскаватор',
      is_active: true,
      created_at: '2026-03-01T10:00:00Z',
      updated_at: '2026-03-01T10:00:00Z',
    },
    created_at: '2026-03-11T10:00:00Z',
    updated_at: '2026-03-31T09:30:00Z',
    monitoringStatus: 'warning',
    warningCount: 2,
    criticalCount: 0,
    lastEvaluatedAt: '2026-04-01T07:42:00Z',
  },
  {
    id: 'demo-eq-2',
    name: 'Самосвал HT-118',
    code: 'HT-118',
    serial_number: 'SN-HT-118',
    location: 'Южная транспортная линия',
    description: 'Тяжелый карьерный самосвал на производственном маршруте.',
    specifications: {
      payload_tons: 190,
      engine_power_kw: 1490,
      tire_size: '59/80R63',
    },
    is_active: true,
    equipment_type: {
      id: 'demo-haul-truck',
      name: 'Самосвал',
      code: 'HT',
      description: 'Карьерный самосвал',
      is_active: true,
      created_at: '2026-03-01T10:00:00Z',
      updated_at: '2026-03-01T10:00:00Z',
    },
    created_at: '2026-03-09T10:00:00Z',
    updated_at: '2026-03-31T08:10:00Z',
    monitoringStatus: 'critical',
    warningCount: 1,
    criticalCount: 1,
    lastEvaluatedAt: '2026-04-01T07:48:00Z',
  },
  {
    id: 'demo-eq-3',
    name: 'Буровая установка DR-32',
    code: 'DR-32',
    serial_number: 'SN-DR-032',
    location: 'Западный уступ / Взрывная зона 3',
    description: 'Автономная буровая установка для буровзрывных работ.',
    specifications: {
      drill_depth_m: 18,
      compressor_bar: 24,
      mast_height_m: 11,
    },
    is_active: true,
    equipment_type: {
      id: 'demo-drill',
      name: 'Буровая установка',
      code: 'DR',
      description: 'Поверхностная буровая установка',
      is_active: true,
      created_at: '2026-03-01T10:00:00Z',
      updated_at: '2026-03-01T10:00:00Z',
    },
    created_at: '2026-03-12T10:00:00Z',
    updated_at: '2026-03-31T11:15:00Z',
    monitoringStatus: 'normal',
    warningCount: 0,
    criticalCount: 0,
    lastEvaluatedAt: '2026-04-01T07:30:00Z',
  },
  {
    id: 'demo-eq-4',
    name: 'Самосвал HT-104',
    code: 'HT-104',
    serial_number: 'SN-HT-104',
    location: 'Маршрут транспортировки руды',
    description: 'Единица парка с историей повышенной температуры двигателя.',
    specifications: {
      payload_tons: 190,
      engine_power_kw: 1490,
      cycle_target_min: 18,
    },
    is_active: true,
    equipment_type: {
      id: 'demo-haul-truck',
      name: 'Самосвал',
      code: 'HT',
      description: 'Карьерный самосвал',
      is_active: true,
      created_at: '2026-03-01T10:00:00Z',
      updated_at: '2026-03-01T10:00:00Z',
    },
    created_at: '2026-03-08T10:00:00Z',
    updated_at: '2026-03-31T07:55:00Z',
    monitoringStatus: 'warning',
    warningCount: 1,
    criticalCount: 0,
    lastEvaluatedAt: '2026-04-01T07:12:00Z',
  },
  {
    id: 'demo-eq-5',
    name: 'Экскаватор EX-188',
    code: 'EX-188',
    serial_number: 'SN-EX-188',
    location: 'Центральный карьер',
    description: 'Вспомогательный экскаватор для вторичного потока материала.',
    specifications: {
      engine_power_kw: 620,
      bucket_capacity_m3: 4.8,
      weight_tons: 79,
    },
    is_active: true,
    equipment_type: {
      id: 'demo-excavator',
      name: 'Экскаватор',
      code: 'EXC',
      description: 'Гусеничный гидравлический экскаватор',
      is_active: true,
      created_at: '2026-03-01T10:00:00Z',
      updated_at: '2026-03-01T10:00:00Z',
    },
    created_at: '2026-03-15T10:00:00Z',
    updated_at: '2026-03-31T12:20:00Z',
    monitoringStatus: 'normal',
    warningCount: 0,
    criticalCount: 0,
    lastEvaluatedAt: '2026-04-01T07:34:00Z',
  },
  {
    id: 'demo-eq-6',
    name: 'Буровая установка DR-21',
    code: 'DR-21',
    serial_number: 'SN-DR-021',
    location: 'Южный уступ',
    description: 'Установка сейчас находится в окне профилактической проверки.',
    specifications: {
      drill_depth_m: 16,
      compressor_bar: 21,
      mast_height_m: 10,
    },
    is_active: true,
    equipment_type: {
      id: 'demo-drill',
      name: 'Буровая установка',
      code: 'DR',
      description: 'Поверхностная буровая установка',
      is_active: true,
      created_at: '2026-03-01T10:00:00Z',
      updated_at: '2026-03-01T10:00:00Z',
    },
    created_at: '2026-03-16T10:00:00Z',
    updated_at: '2026-03-31T13:40:00Z',
    monitoringStatus: 'warning',
    warningCount: 1,
    criticalCount: 0,
    lastEvaluatedAt: '2026-04-01T07:20:00Z',
  },
]

export const demoEquipmentDetails = {
  'demo-eq-1': {
    ...demoEquipmentList[0],
    monitoringState: {
      equipment: demoEquipmentList[0],
      status: 'warning',
      warning_count: 2,
      critical_count: 0,
      last_evaluated_at: '2026-04-01T07:42:00Z',
      updated_at: '2026-04-01T07:42:00Z',
      parameter_states: [
        {
          id: 'demo-parameter-state-1',
          parameter: {
            id: 'param-temperature',
            name: 'Температура гидросистемы',
            code: 'hyd_temp',
            unit: 'C',
            description: 'Температура гидросистемы',
            is_active: true,
            created_at: '2026-03-01T00:00:00Z',
            updated_at: '2026-03-01T00:00:00Z',
          },
          latest_telemetry_reading_id: 'reading-1',
          threshold_rule_id: 'rule-1',
          value: 87.2,
          status: 'warning',
          measured_at: '2026-04-01T07:40:00Z',
          updated_at: '2026-04-01T07:40:00Z',
        },
        {
          id: 'demo-parameter-state-2',
          parameter: {
            id: 'param-vibration',
            name: 'Вибрация основной стрелы',
            code: 'boom_vibration',
            unit: 'mm/s',
            description: 'Тренд вибрации на основной стреле',
            is_active: true,
            created_at: '2026-03-01T00:00:00Z',
            updated_at: '2026-03-01T00:00:00Z',
          },
          latest_telemetry_reading_id: 'reading-2',
          threshold_rule_id: 'rule-2',
          value: 6.1,
          status: 'warning',
          measured_at: '2026-04-01T07:42:00Z',
          updated_at: '2026-04-01T07:42:00Z',
        },
        {
          id: 'demo-parameter-state-3',
          parameter: {
            id: 'param-pressure',
            name: 'Давление гидросистемы',
            code: 'hyd_pressure',
            unit: 'bar',
            description: 'Давление в основном гидравлическом контуре',
            is_active: true,
            created_at: '2026-03-01T00:00:00Z',
            updated_at: '2026-03-01T00:00:00Z',
          },
          latest_telemetry_reading_id: 'reading-3',
          threshold_rule_id: 'rule-3',
          value: 242.5,
          status: 'normal',
          measured_at: '2026-04-01T07:41:00Z',
          updated_at: '2026-04-01T07:41:00Z',
        },
      ],
    },
  },
  'demo-eq-2': {
    ...demoEquipmentList[1],
    monitoringState: {
      equipment: demoEquipmentList[1],
      status: 'critical',
      warning_count: 1,
      critical_count: 1,
      last_evaluated_at: '2026-04-01T07:48:00Z',
      updated_at: '2026-04-01T07:48:00Z',
      parameter_states: [
        {
          id: 'demo-parameter-state-4',
          parameter: {
            id: 'param-engine-temp',
            name: 'Температура двигателя',
            code: 'engine_temp',
            unit: 'C',
            description: 'Температура двигателя',
            is_active: true,
            created_at: '2026-03-01T00:00:00Z',
            updated_at: '2026-03-01T00:00:00Z',
          },
          latest_telemetry_reading_id: 'reading-4',
          threshold_rule_id: 'rule-4',
          value: 109.7,
          status: 'critical',
          measured_at: '2026-04-01T07:48:00Z',
          updated_at: '2026-04-01T07:48:00Z',
        },
        {
          id: 'demo-parameter-state-5',
          parameter: {
            id: 'param-load',
            name: 'Отклонение загрузки',
            code: 'payload_dev',
            unit: '%',
            description: 'Отклонение от плановой загрузки',
            is_active: true,
            created_at: '2026-03-01T00:00:00Z',
            updated_at: '2026-03-01T00:00:00Z',
          },
          latest_telemetry_reading_id: 'reading-5',
          threshold_rule_id: 'rule-5',
          value: 12.8,
          status: 'warning',
          measured_at: '2026-04-01T07:44:00Z',
          updated_at: '2026-04-01T07:44:00Z',
        },
      ],
    },
  },
}

export const demoEvents = [
  {
    id: 'demo-event-1',
    event_type: 'parameter_critical',
    severity: 'critical',
    title: 'Температура двигателя вышла в критический диапазон',
    message: 'HT-118 превышал критический порог температуры двигателя в течение 7 минут.',
    created_at: '2026-04-01T07:48:00Z',
    equipment: demoEquipmentList[1],
    parameter: {
      id: 'param-engine-temp',
      name: 'Температура двигателя',
      code: 'engine_temp',
      unit: 'C',
    },
  },
  {
    id: 'demo-event-2',
    event_type: 'equipment_warning',
    severity: 'warning',
    title: 'Экскаватор EX-204 перешел в состояние предупреждения',
    message: 'Два контролируемых параметра вышли за пределы номинального диапазона.',
    created_at: '2026-04-01T07:42:00Z',
    equipment: demoEquipmentList[0],
    parameter: null,
  },
  {
    id: 'demo-event-3',
    event_type: 'equipment_recovered',
    severity: 'info',
    title: 'Буровая установка DR-32 восстановилась до нормы',
    message: 'Показания вибрации и давления вернулись к базовому уровню.',
    created_at: '2026-04-01T07:30:00Z',
    equipment: demoEquipmentList[2],
    parameter: null,
  },
  {
    id: 'demo-event-4',
    event_type: 'parameter_warning',
    severity: 'warning',
    title: 'Вибрация стрелы приближается к сервисному порогу',
    message: 'Тренд вибрации EX-204 остается выше предупреждающей границы.',
    created_at: '2026-04-01T07:22:00Z',
    equipment: demoEquipmentList[0],
    parameter: {
      id: 'param-vibration',
      name: 'Вибрация основной стрелы',
      code: 'boom_vibration',
      unit: 'mm/s',
    },
  },
  {
    id: 'demo-event-5',
    event_type: 'equipment_warning',
    severity: 'warning',
    title: 'Буровая установка DR-21 требует проверки',
    message: 'Давление компрессора нестабильно во время стартового цикла.',
    created_at: '2026-04-01T07:20:00Z',
    equipment: demoEquipmentList[5],
    parameter: null,
  },
  {
    id: 'demo-event-6',
    event_type: 'parameter_warning',
    severity: 'warning',
    title: 'Температура гидросистемы растет на HT-104',
    message: 'Температура остается выше настроенного предупреждающего максимума.',
    created_at: '2026-04-01T07:12:00Z',
    equipment: demoEquipmentList[3],
    parameter: {
      id: 'param-hyd-temp',
      name: 'Температура гидросистемы',
      code: 'hyd_temp',
      unit: 'C',
    },
  },
]

export const demoMaintenanceTasks = [
  {
    id: 'demo-task-1',
    equipment: demoEquipmentList[1],
    status: 'in_progress',
    priority: 'high',
    title: 'Проверить контур охлаждения двигателя',
    description: 'Проверить поток охлаждающей жидкости, вентиляторный узел и загрязнение радиатора.',
    due_at: '2026-04-01T10:30:00Z',
    created_by_user: {
      id: 'user-manager',
      username: 'ops.manager',
      email: 'manager@example.com',
      first_name: 'Olivia',
      last_name: 'Stone',
      is_active: true,
    },
    assigned_to_user: {
      id: 'user-tech-1',
      username: 'tech.rivera',
      email: 'rivera@example.com',
      first_name: 'Lena',
      last_name: 'Rivera',
      is_active: true,
    },
    created_at: '2026-04-01T06:55:00Z',
    updated_at: '2026-04-01T07:05:00Z',
    completed_at: null,
    plan: null,
  },
  {
    id: 'demo-task-2',
    equipment: demoEquipmentList[0],
    status: 'open',
    priority: 'medium',
    title: 'Проверить гидравлические демпферы',
    description: 'Осмотреть демпферы и подтвердить корректность крепления датчика вибрации.',
    due_at: '2026-04-02T08:00:00Z',
    created_by_user: null,
    assigned_to_user: {
      id: 'user-tech-2',
      username: 'tech.kim',
      email: 'kim@example.com',
      first_name: 'Daniel',
      last_name: 'Kim',
      is_active: true,
    },
    created_at: '2026-03-31T14:20:00Z',
    updated_at: '2026-03-31T14:20:00Z',
    completed_at: null,
    plan: null,
  },
  {
    id: 'demo-task-3',
    equipment: demoEquipmentList[5],
    status: 'open',
    priority: 'medium',
    title: 'Проверить стабильность давления компрессора',
    description: 'Проанализировать стартовый тренд давления и осмотреть воздушные магистрали.',
    due_at: '2026-04-03T09:00:00Z',
    created_by_user: null,
    assigned_to_user: null,
    created_at: '2026-03-31T12:50:00Z',
    updated_at: '2026-03-31T12:50:00Z',
    completed_at: null,
    plan: null,
  },
  {
    id: 'demo-task-4',
    equipment: demoEquipmentList[2],
    status: 'done',
    priority: 'low',
    title: 'Послесменный осмотр буровой мачты',
    description: 'Плановый визуальный осмотр после сигнала о повышенной вибрации.',
    due_at: '2026-03-31T19:00:00Z',
    created_by_user: null,
    assigned_to_user: {
      id: 'user-tech-3',
      username: 'tech.ward',
      email: 'ward@example.com',
      first_name: 'Ava',
      last_name: 'Ward',
      is_active: true,
    },
    created_at: '2026-03-31T07:00:00Z',
    updated_at: '2026-03-31T18:40:00Z',
    completed_at: '2026-03-31T18:40:00Z',
    plan: null,
  },
]

export const demoNotifications = [
  {
    id: 'demo-notification-1',
    notification_type: 'event_critical',
    channel: 'internal',
    title: 'Критическое событие по HT-118',
    message: 'Температура двигателя выше критического порога.',
    is_read: false,
    read_at: null,
    delivered_at: '2026-04-01T07:48:20Z',
    created_at: '2026-04-01T07:48:00Z',
    recipient_user: demoMaintenanceTasks[0].assigned_to_user,
    event: demoEvents[0],
    maintenance_task: null,
  },
  {
    id: 'demo-notification-2',
    notification_type: 'maintenance_due',
    channel: 'email',
    title: 'Техническое обслуживание запланировано на это утро',
    message: 'Проверка контура охлаждения HT-118 должна быть выполнена до 10:30.',
    is_read: false,
    read_at: null,
    delivered_at: '2026-04-01T07:02:00Z',
    created_at: '2026-04-01T06:58:00Z',
    recipient_user: demoMaintenanceTasks[0].assigned_to_user,
    event: null,
    maintenance_task: demoMaintenanceTasks[0],
  },
  {
    id: 'demo-notification-3',
    notification_type: 'event_warning',
    channel: 'internal',
    title: 'Предупреждающий тренд по EX-204',
    message: 'Температура гидросистемы и вибрация стрелы требуют внимания.',
    is_read: true,
    read_at: '2026-04-01T07:45:00Z',
    delivered_at: '2026-04-01T07:42:20Z',
    created_at: '2026-04-01T07:42:00Z',
    recipient_user: demoMaintenanceTasks[1].assigned_to_user,
    event: demoEvents[1],
    maintenance_task: null,
  },
  {
    id: 'demo-notification-4',
    notification_type: 'event_recovery',
    channel: 'internal',
    title: 'DR-32 вернулась в норму',
    message: 'Восстановившееся оборудование можно вернуть в производственный план.',
    is_read: true,
    read_at: '2026-04-01T07:36:00Z',
    delivered_at: '2026-04-01T07:30:30Z',
    created_at: '2026-04-01T07:30:00Z',
    recipient_user: demoMaintenanceTasks[3].assigned_to_user,
    event: demoEvents[2],
    maintenance_task: null,
  },
]

export const demoUnreadNotificationCount = {
  unread_count: 2,
}

export function findDemoEquipmentDetails(equipmentId) {
  return demoEquipmentDetails[equipmentId] ?? null
}
