"""Backward-compatible model import module."""

from app.models import (
    AuditLog,
    Equipment,
    EquipmentParameterState,
    EquipmentState,
    Event,
    EquipmentType,
    EquipmentTypeParameter,
    MaintenancePlan,
    MaintenanceRecord,
    MaintenanceTask,
    Notification,
    Parameter,
    Permission,
    Role,
    RolePermission,
    TelemetryEvaluation,
    TelemetryReading,
    ThresholdRule,
    User,
    UserRole,
)

__all__ = [
    "AuditLog",
    "Equipment",
    "EquipmentParameterState",
    "EquipmentState",
    "Event",
    "EquipmentType",
    "EquipmentTypeParameter",
    "MaintenancePlan",
    "MaintenanceRecord",
    "MaintenanceTask",
    "Notification",
    "Parameter",
    "Permission",
    "Role",
    "RolePermission",
    "TelemetryEvaluation",
    "TelemetryReading",
    "ThresholdRule",
    "User",
    "UserRole",
]
