"""Event type constants for monitoring transitions."""

EVENT_TYPE_PARAMETER_WARNING = "parameter_warning"
EVENT_TYPE_PARAMETER_CRITICAL = "parameter_critical"
EVENT_TYPE_PARAMETER_RECOVERED = "parameter_recovered"
EVENT_TYPE_EQUIPMENT_WARNING = "equipment_warning"
EVENT_TYPE_EQUIPMENT_CRITICAL = "equipment_critical"
EVENT_TYPE_EQUIPMENT_RECOVERED = "equipment_recovered"

VALID_EVENT_TYPES = (
    EVENT_TYPE_PARAMETER_WARNING,
    EVENT_TYPE_PARAMETER_CRITICAL,
    EVENT_TYPE_PARAMETER_RECOVERED,
    EVENT_TYPE_EQUIPMENT_WARNING,
    EVENT_TYPE_EQUIPMENT_CRITICAL,
    EVENT_TYPE_EQUIPMENT_RECOVERED,
)
