"""Shared maintenance domain constants."""

MAINTENANCE_TASK_STATUS_OPEN = "open"
MAINTENANCE_TASK_STATUS_IN_PROGRESS = "in_progress"
MAINTENANCE_TASK_STATUS_DONE = "done"
MAINTENANCE_TASK_STATUS_CANCELLED = "cancelled"

VALID_MAINTENANCE_TASK_STATUSES = (
    MAINTENANCE_TASK_STATUS_OPEN,
    MAINTENANCE_TASK_STATUS_IN_PROGRESS,
    MAINTENANCE_TASK_STATUS_DONE,
    MAINTENANCE_TASK_STATUS_CANCELLED,
)

MAINTENANCE_TASK_PRIORITY_LOW = "low"
MAINTENANCE_TASK_PRIORITY_MEDIUM = "medium"
MAINTENANCE_TASK_PRIORITY_HIGH = "high"

VALID_MAINTENANCE_TASK_PRIORITIES = (
    MAINTENANCE_TASK_PRIORITY_LOW,
    MAINTENANCE_TASK_PRIORITY_MEDIUM,
    MAINTENANCE_TASK_PRIORITY_HIGH,
)
