"""Shared notification domain constants."""

NOTIFICATION_CHANNEL_INTERNAL = "internal"
NOTIFICATION_CHANNEL_EMAIL = "email"

VALID_NOTIFICATION_CHANNELS = (
    NOTIFICATION_CHANNEL_INTERNAL,
    NOTIFICATION_CHANNEL_EMAIL,
)

NOTIFICATION_TYPE_EVENT_CRITICAL = "event_critical"
NOTIFICATION_TYPE_EVENT_WARNING = "event_warning"
NOTIFICATION_TYPE_UPCOMING_MAINTENANCE = "upcoming_maintenance"
NOTIFICATION_TYPE_MANUAL = "manual"

VALID_NOTIFICATION_TYPES = (
    NOTIFICATION_TYPE_EVENT_CRITICAL,
    NOTIFICATION_TYPE_EVENT_WARNING,
    NOTIFICATION_TYPE_UPCOMING_MAINTENANCE,
    NOTIFICATION_TYPE_MANUAL,
)

UPCOMING_MAINTENANCE_WINDOW_DAYS = 3
